### WORK IN PROGRESS ###

import click
import uvicorn
from a2a.server.apps import A2AStarletteApplication
from a2a.server.request_handlers import DefaultRequestHandler
from a2a.server.tasks import InMemoryTaskStore
from a2a.types import AgentCapabilities, AgentCard, AgentSkill
from agent_executor import BillingAgentExecutor
from ...resarch_agent.agent_executor import ResearchAgentExecutor


@click.command()
@click.option('--host', default='localhost')
@click.option('--port', default=10000)
@click.option(
    '--research-agent', 'research_agent', default='http://localhost:10002'
)

def main(host, port, research_agent):
    # 1. 스킬 메타데이터 설정
    skill = AgentSkill(
        id="billing",
        name="Billing",
        description="arXiv의 관련 학술 논문을 바탕으로 연구 동향 분석합니다",
        input_modes=["text/plain"],
        output_modes=["text/plain"]
    )
    # 2. A2A 에이전트 서버 생성
    agent_card = AgentCard(
        name="BillingAgent",
        description="Agent that deploys a smart contract that bills users for content generated by ResearchAgent",
        url=f'http://{host}:{port}/',
        version="1.0.0",
        defaultInputModes=['text'],
        defaultOutputModes=['text'],
        capabilities=AgentCapabilities(streaming=True),
        skills=[skill]
    )
    # 3. 에이전트 서버 실행
    request_handler = DefaultRequestHandler(
        agent_executor=BillingAgentExecutor(research_agent),
        task_store=InMemoryTaskStore(),
    )
    server = A2AStarletteApplication(
        agent_card=agent_card,
        http_handler=request_handler
    )
    uvicorn.run(server.build(), host=host, port=port)


if __name__ == '__main__':
    main()


# TODO: interact with user agent
# TODO: interact with research agent